# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    # We use mambaforge to install packages from conda-forge below
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      # Build unidist to make C++ extensions available and also
      # for correct module imports when building the documentation.
      - pip install --no-cache-dir -e .
sphinx:
   configuration: docs/conf.py
   # TODO: Fix #156 and set to true
   fail_on_warning: false

formats:
  - epub
  - pdf

# We use dependencies from conda-forge to have a ready-to-use MPI implementation.
# If we tried to install mpi4py from PyPI, installation would fail because
# mpi4py requires a working MPI implementation installed beforehand.
conda:
  environment: environment_linux.yml
